# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: update-git
          command: 'sudo add-apt-repository ppa:git-core/ppa -y && sudo apt-get update && sudo apt-get install git -y && git --version'

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v8-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v8-dependencies-

      - run:
          name: install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v7-dependencies-{{ checksum "package-lock.json" }}

      - run: # run AOT build
          name: build
          command: npm run build

      - run: # run unit tests
          name: test
          command: npm run test

      - run:  # check formatting
          name: format
          command: npm run format:check

      - run:  # check lint errors
          name: lint
          command: npm run lint
